# 偏函数

Python 的`functools`模块提供了很多有用的功能，其中一个就是偏函数 `functools.partial`。

对于某些含有默认参数的函数，`functools.partial` 可以通过设置这些默认参数的值来直接生成新的函数：

```python
def to_1d(arg: tp.ArrayLike, raw: bool = False) -> tp.AnyArray1d:
    arg = to_any_array(arg, raw=raw)
    if arg.ndim == 2:
        if arg.shape[1] == 1:
            if checks.is_frame(arg):
                return arg.iloc[:, 0]
            return arg[:, 0]
    if arg.ndim == 1:
        return arg
    elif arg.ndim == 0:
        return arg.reshape((1,))
    raise ValueError(f"Cannot reshape a {arg.ndim}-dimensional array to 1 dimension")

to_1d_array = functools.partial(to_1d, raw=True)

```

# 肉眼分析 `numpy.ndarray` 的 `shape`

例如：

```python
[[[[ 0  1]   
   [ 2  3]   
   [ 4  5]   
   [ 6  7]] 
              
              

  [[ 8  9]   
   [10 11]   
   [12 13]   
   [14 15]]] 
              


 [[[16 17]   
   [18 19]   
   [20 21]   
   [22 23]]

  [[24 25]   
   [26 27]   
   [28 29]
   [30 31]]]


 [[[32 33]   
   [34 35]   
   [36 37]   
   [38 39]]

  [[40 41]   
   [42 43]   
   [44 45]
   [46 47]]]]
```
- （1）先通过最外层 `[]` 的数目判断 `ndim`，这个例子中是 4，所以应该是 `(*, *, *, *)`；
- （2）脱去最外层 `[]`，应该类似于 `..., ..., ...`，看有几个，这里是 3，所以应该是 `(3, *, *, *)`；
- （3）选取（2）中任一个，继续脱去最外层 `[]`，看有几个，这里是 2，所以应该是 `(3, 2, *, *)`；
- （4）如此循环 ...，可以得到 `shape` 是 `(3, 2, 4, 2)`。